form941-sdk/Form941SDK/Models/Business/BusinessCreateRequest.cs
namespace Form941SDK.Models.Business
{
    public class BusinessCreateRequest:Business
    {
    }
}

form941-sdk/Form941SDK/Models/Business/BusinessCreateResponse.cs
using Form941SDK.Models.Base;
using System.Runtime.Serialization;

namespace Form941SDK.Models.Business
{
    public class BusinessCreateResponse : BaseResponseStatus
    {
        /// <summary>
        /// Business Identifier
        /// </summary>
        [DataMember(Order = 1)]
        public Guid BusinessId { get; set; }

        [DataMember(Order = 2)]
        public string PayerRef { get; set; }

        [DataMember(Order = 3)]
        public bool IsEIN { get; set; }

        [DataMember(Order = 4)]
        public string EINorSSN { get; set; }

        [DataMember(Order = 5)]
        public string BusinessNm { get; set; }
        [DataMember(Order = 6)]
        public string FirstNm { get; set; }
        [DataMember(Order = 7)]
        public string LastNm { get; set; }
        [DataMember(Order = 8)]
        public string MiddleNm { get; set; }
        [DataMember(Order = 9)]
        public string Suffix { get; set; }

        [DataMember(Order = 10)]
        public List<Error> Errors { get; set; }
    }
}

form941-sdk/Form941SDK/Models/Business/BusinessListResponse.cs
using Form941SDK.Models.Base;
using System.Runtime.Serialization;

namespace Form941SDK.Models.Business
{
    public class BusinessListResponse : BaseResponseStatus
    {
        /// <summary>
        /// Business Details of all the business
        /// </summary>
        [DataMember(Order = 1)]
        public List<Business> Businesses { get; set; }
        public List<Error> Errors { get; set; }
    }
}

form941-sdk/Form941SDK/Models/Business/Form941ReturnHeader.cs
using Form941SDK.Models.Form941Create;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Form941SDK.Models.Business
{
    [DataContract]
    public class Form941ReturnHeader
    {
        /// <summary>
        /// Return type. The form types can be FORM941, FORM941PR, or FORM941SS.
        /// </summary>
        [DataMember]
        //[Required(ErrorMessage = "ERR-RETURNTYPE-01:Return Type is Required")]
        //[MaxLength(15, ErrorMessage = "ERR-RETURNTYPE-02:Maximum 15 characters only allowed")]
        public string ReturnType { get; set; }

        /// <summary>
        /// Maximum of 1000 clients can be sent in one submission. If there are more than 1000 Clients for Schedule R, the submissions have to be multiple with the value "True". The submission with the final list of clients should have the value "False"
        /// </summary>

        [DataMember]
        public bool MoreClients { get; set; }


        /// <summary>
        ///  Form 941 Tax Year
        /// </summary>
        [DataMember]
        public string TaxYr { get; set; }

        /// <summary>
        /// Form 941 Filing Quarter 
        /// </summary>
        [DataMember]
        //[Required(ErrorMessage = "ERR-QUARTER-01:Filling Quarter is Required")]
        //[MaxLength(2, ErrorMessage = "ERR-QUARTER-02:Denote the Filing Quarter in 2 characters only")]
        //[RegularExpression("([Q|q][1-4]+$)", ErrorMessage = "ERR-QUARTER-04:Enter a valid Form 941 Filing Quarter")]
        public string Qtr { get; set; }

        /// <summary>
        /// Business Details
        /// </summary>
        [DataMember]
        public Business Business { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [DataMember]
        public bool IsThirdPartyDesignee { get; set; }

        /// <summary>
        /// Third Party Designee Details
        /// </summary>
        [DataMember]
        public ThirdPartyDesignee ThirdPartyDesignee { get; set; }

        /// <summary>
        /// Online Signature PIN or Reporting Agent PIN 
        /// </summary>
        [DataMember]
        public SignatureDetails SignatureDetails { get; set; }

        /// <summary>
        /// Business Status Details
        /// </summary>
        [DataMember]
        public BusinessStatusDetails BusinessStatusDetails { get; set; }
        /// <summary>
        /// 
        /// </summary>



    
    }
}

form941-sdk/Form941SDK/Controllers/BusinessController.cs
using Form941SDK.Models.Business;
using Form941SDK.Models.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;
using Newtonsoft.Json;
using System.Xml;
using static Form941SDK.Models.Base.EntityBase;
using Constants = Form941SDK.Models.Utilities.Constants;
using Formatting = Newtonsoft.Json.Formatting;

namespace Form941SDK.Controllers
{
    public class BusinessController : Controller
    {
        #region Business View Page
        [HttpGet]
        public IActionResult CreateBusiness()
        {
            return View();
        }
        #endregion

        #region Business Create 
        [HttpPost]
        public ActionResult CreateBusiness(BusinessCreateRequest createBusiness)
        {
            var responseJson = string.Empty;
            var businessCreateResponse = new BusinessCreateResponse();
            // Generate JSON for Business
            var requestJson = JsonConvert.SerializeObject(createBusiness, Formatting.Indented);
            //Get Access token from OAuth API response 
            GetAccessToken accessToken = new GetAccessToken(HttpContext);
            string generatedAccessToken = accessToken.GetGeneratedAccessToken();
            if (!string.IsNullOrWhiteSpace(generatedAccessToken))
            {
                using (var apiClient = new HttpClient())
                {
                    //API URL to Business Create
                    string requestUri = Constants.CREATE_BUSINESS;
                    //Get APIUrl From Appsetting 
                    apiClient.BaseAddress = new Uri(Utility.GetAppSettings(Constants.TBS_PUBLIC_API_BASE_URL));
                    //Construct HTTP headers in Generated Token.
                    OAuthGenerator.ConstructHeadersWithAccessToken(apiClient, generatedAccessToken);
                    //Create Response from API
                    var apiResponse = apiClient.PostAsJsonAsync(requestUri, createBusiness).Result;
                    if (apiResponse != null && apiResponse.IsSuccessStatusCode)
                    {
                        //Read Response 
                        var createResponse = apiResponse.Content.ReadAsAsync
                        <BusinessCreateResponse>
                        ().Result;
                        if (createResponse != null)
                        {
                            responseJson = JsonConvert.SerializeObject(createResponse, Formatting.Indented);
                            //Deserializing JSON (Success Response) to BusinessCreateResponse object
                            businessCreateResponse = JsonConvert.DeserializeObject
                            <BusinessCreateResponse>
                            (responseJson);
                        }
                    }
                    else
                    {
                        var createResponse = apiResponse.Content.ReadAsAsync<Object>().Result;
                        responseJson = JsonConvert.SerializeObject(createResponse, Formatting.Indented);
                        //Deserializing JSON (Error Response) to BusinessCreateResponse object
                        businessCreateResponse = JsonConvert.DeserializeObject
                        <BusinessCreateResponse>
                        (responseJson);
                    }
                }
            }
            return PartialView("_BusinessCreateResponse", businessCreateResponse);
        }
        #endregion

        #region Get Business List
        [HttpGet]
        public ActionResult GetBusinessList()
        {
            var businessListResponse = new BusinessListResponse();
            var business = new List <Business>();
            var getResponseJSON = string.Empty;
            //Get URLs from App.Config
            string apiUrl = Utility.GetAppSettings(Constants.TBS_PUBLIC_API_BASE_URL);
            //Get Access token from GetAccessToken Class
            GetAccessToken accessToken = new GetAccessToken(HttpContext);
            //Get Access token from OAuth API response
            var generatedAccessToken = accessToken.GetGeneratedAccessToken();
            if (!string.IsNullOrWhiteSpace(generatedAccessToken))
            {
                using (var apiClient = new HttpClient())
                {
                    //API URL to Get Business List Return
                    string requestUri = Constants.BUSINESS_LIST + "?Page=1&PageSize=10";
                    apiClient.BaseAddress = new Uri(apiUrl);
                    //Construct HTTP headers
                    OAuthGenerator.ConstructHeadersWithAccessToken(apiClient, generatedAccessToken);
                    //Get Response
                    var apiResponse = apiClient.GetAsync(requestUri).Result;
                    if (apiResponse != null && apiResponse.IsSuccessStatusCode)
                    {
                        //Read Response from API
                        var listResponse = apiResponse.Content.ReadAsAsync
                        <BusinessListResponse>
                        ().Result;
                        if (listResponse != null)
                        {
                            getResponseJSON = JsonConvert.SerializeObject(listResponse, Formatting.Indented);
                            businessListResponse = JsonConvert.DeserializeObject
                            <BusinessListResponse>
                            (getResponseJSON);
                        }
                    }
                    else
                    {
                        //Read Response from API
                        var listResponse = apiResponse.Content.ReadAsAsync<Object>().Result;
                        getResponseJSON = JsonConvert.SerializeObject(listResponse, Formatting.Indented);
                        businessListResponse = JsonConvert.DeserializeObject
                        <BusinessListResponse>
                        (getResponseJSON);
                    }
                }
            }
            return View("GetBusinessList", businessListResponse);
        }
        #endregion

        #region  Business Members Type  based on Business Type
        [HttpGet]
        public ActionResult BusinessMembersType(string SelectedBusinessTypeVal)
        {
            var businessType = SelectedBusinessTypeVal;
            if (!string.IsNullOrWhiteSpace(businessType))
            {
                var businessMembersList = new List
                <SelectListItem>
                ();
                #region DropDownValues for Business MemberType
                if (businessType == BusinessType.ESTE.ToString())
                {
                    //Assign Values from EstateBusinessMembers Enum to te List
                    businessMembersList = Enum.GetValues(typeof(EstateBusinessMembers)).Cast
                    <EstateBusinessMembers>
                    ().Select(x => new SelectListItem { Text = Utility.GetEnumDisplayName(x), Value = (x).ToString() }).ToList();
                }
                else if (businessType == BusinessType.PART.ToString())
                {
                    //Assign Values from PartnershipBusinessMembers Enum to te List
                    businessMembersList = Enum.GetValues(typeof(PartnershipBusinessMembers)).Cast
                    <PartnershipBusinessMembers>
                    ().Select(x => new SelectListItem { Text = Utility.GetEnumDisplayName(x), Value = (x).ToString() }).ToList();
                }
                else if (businessType == BusinessType.CORP.ToString())
                {
                    //Assign Values from CorporationBusinessMembers Enum to te List
                    businessMembersList = Enum.GetValues(typeof(CorporationBusinessMembers)).Cast
                    <CorporationBusinessMembers>
                    ().Select(x => new SelectListItem { Text = Utility.GetEnumDisplayName(x), Value = (x).ToString() }).ToList();
                }
                else if (businessType == BusinessType.EORG.ToString())
                {
                    //Assign Values from ExemptOrganizationBusinessMembers Enum to te List
                    businessMembersList = Enum.GetValues(typeof(ExemptOrganizationBusinessMembers)).Cast
                    <ExemptOrganizationBusinessMembers>
                    ().Select(x => new SelectListItem { Text = Utility.GetEnumDisplayName(x), Value = (x).ToString() }).ToList();
                }
                else if (businessType == BusinessType.SPRO.ToString())
                {
                    //Assign Values from SoleProprietorshipBusinessMembers Enum to te List
                    businessMembersList = Enum.GetValues(typeof(SoleProprietorshipBusinessMembers)).Cast
                    <SoleProprietorshipBusinessMembers>
                    ().Select(x => new SelectListItem { Text = Utility.GetEnumDisplayName(x), Value = (x).ToString() }).ToList();
                }
                return new JsonResult(new { data = businessMembersList });
                #endregion
            }
            return new JsonResult(false);
        }
        #endregion
    }
}

form941-sdk/Form941SDK/Views/Business/GetBusinessList.cshtml
@model Form941SDK.Models.Business.BusinessListResponse
@using Form941SDK.Models.Utilities
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    @if (Model != null)
    {
        <div class='d-flex align-items-center justify-content-between mt-5 pt-2'>
            <div>
                <h1 class='head-1'>Businesses</h1>
                <div class="heading-bottom-line position-relative pb-0  mb-3"></div>
            </div>
            <div>
                <button class="btn btn_primary shadow btn_md float-right" style="float: right;" onclick="location.href='@Url.Action("CreateBusiness", "Business")'"> Create Business</button>
            </div>
        </div>
        <table class="table table-striped mt-4 table-bordered text-center">
            <tr>
                <th class="text-center">Business Id</th>
                <th class="text-center">Business Name</th>
                <th class="text-center">First Name</th>
                <th class="text-center">Last Name</th>
                <th class="text-center">Middle Name</th>
                <th class="text-center">Suffix</th>
                <th class="text-center">Email</th>
                <th class="text-center">Action</th>
            </tr>
            <tbody>
                @foreach (var BizDetails in Model.Businesses)
                {
                    <tr>
                        <td style="text-align:left">
                            @BizDetails.BusinessId
                        </td>
                        <td style="text-align:left">
                            @BizDetails.BusinessNm
                        </td>
                        <td style="text-align:left">
                            @BizDetails.FirstNm
                        </td>
                        <td style="text-align:left">
                            @BizDetails.LastNm
                        </td>
                        <td style="text-align:left">
                            @BizDetails.MiddleNm
                        </td>
                        <td style="text-align:left">
                            @BizDetails.Suffix
                        </td>
                        <td style="text-align:left">
                            @BizDetails.Email
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary status-btn btn_smm me-2" onclick="location.href='@Url.Action("CreateForm941View", "Form941", new { businessId = BizDetails.BusinessId,businessName=BizDetails.BusinessNm,firstName=BizDetails.FirstNm,lastName=BizDetails.LastNm,middleName=BizDetails.MiddleNm,suffix=BizDetails.Suffix,tin=BizDetails.EINorSSN})'">
                                Create Form941
                            </button>
                            <button type="button" class="btn btn-primary status-btn btn_smm me-2" onclick="location.href='@Url.Action("Get941List", "Form941", new { businessId = BizDetails.BusinessId,businessName=BizDetails.BusinessNm,firstName=BizDetails.FirstNm,lastName=BizDetails.LastNm,middleName=BizDetails.MiddleNm,suffix=BizDetails.Suffix,tin=BizDetails.EINorSSN})'">
                                List
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <button class="btn_cancel mb-3" onclick="location.href='@Url.Action("Index", "Home")'">
            <i class="fa fa-arrow-circle-left"></i>
            Back
        </button>
    }
    else
    {
        <div class="mt-5">
            <div class="d-flex align-items-center justify-content-center">
                <p class="mt-2 mb-0 text-center text-danger fw-600">
                    Before you submit TIN Request in your TaxBandits Account,You Should have atleast one Business in your account. To add a new business, click 'Create Business' button below.
                </p>
            </div>
            <div class="text-center mt-4">
                <button class="btn btn_primary shadow btn_md" onclick="location.href='@Url.Action("CreateBusiness", "Business")'"> Create Business</button>
            </div>
            <div>
                <button class="btn_cancel  mb-3" onclick="location.href='@Url.Action("Index", "Home")'"><i class="fa fa-arrow-circle-left"></i> Back   </button>
            </div>
        </div>
    }
</div>

form941-sdk/Form941SDK/Views/Business/_BusinessCreateResponse.cshtml
@model Form941SDK.Models.Business.BusinessCreateResponse
<div class="modal-header">
    <h5 class="modal-title">Create Business Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    <div class="table-container mt-2 mb-4">
        <table>
            <tbody>
                <tr class="fw-600 ">
                    <th class="text-center fw-600 bg-dull-blue">Status Code</th>
                    <th class="text-center">Status Name</th>
                    <th class="text-center">Status Message</th>
                </tr>
                <tr>
                    <td class="text-center align-top">
                        @Model.StatusCode
                    </td>
                    <td class="text-center align-top">
                        @Model.StatusName
                    </td>
                    @if (Model.StatusCode == 200)
                    {
                        <td class="text-center border-radious-bottom-right align-top text-success">
                            @Model.StatusMessage
                        </td>
                    }
                    else
                    {
                        <td class="text-center border-radious-bottom-right align-top text-danger">
                            @Model.StatusMessage
                        </td>
                    }
                </tr>
            </tbody>
        </table>
    </div>
    @if (Model != null && Model.Errors != null && Model.Errors.Count > 0)
    {
        <h2 class="tabel-sub-head">Error Records</h2>
        <div class="table-container mb-3">
            <table>
                <tbody>
                    <tr class="fw-600 ">
                        <th class="text-center fw-600">Id</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Message</th>
                    </tr>
                    @foreach (var item in Model.Errors)
                    {
                        <tr>
                            <td class="text-center align-top">@item.ID</td>
                            <td class="text-center align-top">@item.Name</td>
                            <td class="text-center border-radious-bottom-right align-top">@item.Message</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    @if (Model != null && Model.StatusCode == 200)
    {
        <h2 class="tabel-sub-head">Success Records</h2>
        <div class="table-container mb-3">
            <table>
                <tbody>
                    <tr class="fw-600 ">
                        <th class="text-center fw-600">Business Id</th>
                        <th class="text-center">IsEIN</th>
                        <th class="text-center">EINorSSN</th>
                        <th class="text-center">BusinessNm</th>
                        <th class="text-center">FirstNm</th>
                        <th class="text-center">LastNm</th>
                        <th class="text-center">MiddleNm</th>
                        <th class="text-center">Suffix</th>
                    </tr>
                    <tr>
                        <td class="text-center align-top">@Model.BusinessId</td>
                        <td class="text-center align-top">@Model.IsEIN</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.EINorSSN</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.BusinessNm</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.FirstNm</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.LastNm</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.MiddleNm</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.Suffix</td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>