form1099K-sdk/Form1099KSDK/Models/Form1099KCreate/Form1099KCreateResponse.cs
using Form1099KSDK.Models.Base;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KCreate
{
    [DataContract]
    public class Form1099KCreateResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public Guid? SubmissionId { get; set; }
        [DataMember(Order = 2)]
        public Guid? BusinessId { get; set; }
        [DataMember(Order = 5)]
        public Form1099KRecords Form1099Records { get; set; }
        [DataMember(Order = 6)]
        public List<ErrorV3> Errors { get; set; }
    }
}

form1099K-sdk/Form1099KSDK/Models/Form1099KCreate/Form1099KValidateFormResponse.cs
using Form1099KSDK.Models.Base;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KCreate
{
    [DataContract]
    public class Form1099KValidateFormResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public List<ErrorKRecords> ErrorRecords { get; set; }
        [DataMember(Order = 2)]
        public List<ErrorV3> Errors { get; set; }
    }
}

form1099K-sdk/Form1099KSDK/Models/Form1099KDelete/Form1099KDeleteResponse.cs
using Form1099KSDK.Models.Base;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KDelete
{
    [DataContract]
    public class Form1099KDeleteResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public Guid? SubmissionId { get; set; }
        [DataMember(Order = 2)]
        public Form1099KResponseRecords Form1099Records { get; set; }
        [DataMember(Order = 4)]
        public List<ErrorV3> Errors { get; set; }
    }
}

form1099K-sdk/Form1099KSDK/Models/Form1099KStatus/Form1099KStatusResponse.cs
using Form1099KSDK.Models.Base;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KStatus
{
    [DataContract]
    public class Form1099KStatusResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public Guid? SubmissionId { get; set; }
        [DataMember(Order = 2)]
        public Guid? BusinessId { get; set; }
        [DataMember(Order = 3)]
        public string PayerRef { get; set; }
        [DataMember(Order = 5)]
        public Form1099KStatusRecords Form1099Records { get; set; }
        [DataMember(Order = 6)]
        public List<ErrorV3> Errors { get; set; }

    }
}

form1099K-sdk/Form1099KSDK/Models/Form1099KTransmit/Form1099KTransmitResponse.cs
using Form1099KSDK.Models.Base;
using Form1099KSDK.Models.Form1099KDelete;
using Form1099KSDK.Models.Form1099KGet;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KTransmit
{
    [DataContract]
    public class Form1099KTransmitResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public Guid? SubmissionId { get; set; }
        [DataMember(Order = 2)]
        public Form1099KResponseRecords Form1099Records { get; set; }
        [DataMember(Order = 3)]
        public List<ErrorV3> Errors { get; set; }
    }
}

form1099K-sdk/Form1099KSDK/Models/Form1099KUpdate/Form1099KUpdateResponse.cs
using Form1099KSDK.Models.Base;
using Form1099KSDK.Models.Form1099KCreate;
using System.Runtime.Serialization;

namespace Form1099KSDK.Models.Form1099KUpdate
{
    [DataContract]
    public class Form1099KUpdateResponse : BaseResponseStatus
    {
        [DataMember(Order = 1)]
        public Guid? SubmissionId { get; set; }
        [DataMember(Order = 2)]
        public Guid? BusinessId { get; set; }
        [DataMember(Order = 5)]
        public Form1099KRecords Form1099Records { get; set; }
        [DataMember(Order = 6)]
        public List<ErrorV3> Errors { get; set; }
    }
}

form1099K-sdk/Form1099KSDK/Controllers/Form1099KController.cs
using Form1099KSDK.Models.Business;
using Form1099KSDK.Models.Form1099KCreate;
using Form1099KSDK.Models.Form1099KDelete;
using Form1099KSDK.Models.Form1099KDraftPdfUrl;
using Form1099KSDK.Models.Form1099KGet;
using Form1099KSDK.Models.Form1099KList;
using Form1099KSDK.Models.Form1099KRequestPdfURL;
using Form1099KSDK.Models.Form1099KStatus;
using Form1099KSDK.Models.Form1099KTransmit;
using Form1099KSDK.Models.Form1099KUpdate;
using Form1099KSDK.Models.Utilities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Form1099KSDK.Controllers
{
    public class Form1099KController : Controller
    {
        #region CreateForm 1099K View
        public ActionResult CreateForm1099K(Guid businessId, string businessName, string firstName, string lastName, string MiddleName, string suffix, string tin)
        {
            if (businessId != Guid.Empty && (!string.IsNullOrWhiteSpace(businessName) || !string.IsNullOrWhiteSpace(firstName) && !string.IsNullOrWhiteSpace(lastName)) && !string.IsNullOrWhiteSpace(tin))
            {
                Form1099KCreateRequest createRequest = new Form1099KCreateRequest { ReturnHeader = new APIReturnHeader { Business = new Business { BusinessId = businessId, BusinessNm = businessName, FirstNm = firstName, LastNm = lastName, MiddleNm= MiddleName, Suffix = suffix,  EINorSSN = tin } } };
                return View(createRequest);
            }
            return View();
        }
        #endregion

        #region Form 1099K Create 
        [HttpPost]
        public ActionResult CreateForm1099K(Form1099KCreateRequest createRequest)
        {
            var form1099KCreateResponseJson = string.Empty;
            var form1099KCreateResponse = new Form1099KCreateResponse();
            //Get APIUrl From Appsetting 
            string ApiUrl = Utility.GetAppSettings(Constants.TBS_PUBLIC_API_BASE_URL);
            //Get Access token from OAuth API response 
            GetAccessToken AccessToken = new GetAccessToken(HttpContext);
            string GeneratedAccessToken = AccessToken.GetGeneratedAccessToken();

            if (!string.IsNullOrWhiteSpace(GeneratedAccessToken))
            {
                using (var apiClient = new HttpClient())
                {
                    //API URL for K Create
                    string requestUri = Constants.CREATE_1099K_URL;
                    apiClient.BaseAddress = new Uri(ApiUrl);
                    //Construct HTTP headers in Generated Token.
                    OAuthGenerator.ConstructHeadersWithAccessToken(apiClient, GeneratedAccessToken);
                    //Post Response from Api
                    var apiResponse = apiClient.PostAsJsonAsync(requestUri, createRequest).Result;

                    if (apiResponse != null && apiResponse.IsSuccessStatusCode)
                    {
                        //Read Response
                        var createResponse = apiResponse.Content.ReadAsAsync<Form1099KCreateResponse>().Result;
                        if (createResponse != null)
                        {
                            form1099KCreateResponseJson = JsonConvert.SerializeObject(createResponse, Formatting.Indented);
                            //Deserializing JSON (Success Response) to form1099KCreateResponse object
                            form1099KCreateResponse = JsonConvert.DeserializeObject<Form1099KCreateResponse>(form1099KCreateResponseJson);
                        }
                    }
                    else
                    {
                        var createResponse = apiResponse.Content.ReadAsAsync<Form1099KCreateResponse>().Result;
                        form1099KCreateResponseJson = JsonConvert.SerializeObject(createResponse, Formatting.Indented);
                        //Deserializing JSON (Error Response) to form1099KCreateResponse object
                        form1099KCreateResponse = JsonConvert.DeserializeObject<Form1099KCreateResponse>(form1099KCreateResponseJson);
                    }
                }
            }

            return PartialView("_Form1099KCreateResponse", form1099KCreateResponse);
        }
        #endregion

        #region Form 1099K List
        [HttpGet]
        public ActionResult GetForm1099KList(Guid businessId, string businessName, string firstName, string lastName, string MiddleName, string suffix, string tin)
        {
            var form1099KListRepsone = new Form1099KListResponse();
            var form1099KListResponseJSON = string.Empty;
            //Get URLs from App.Config
            string apiUrl = Utility.GetAppSettings(Constants.TBS_PUBLIC_API_BASE_URL);
            //Get Access token from GetAccessToken Class
            GetAccessToken accessToken = new GetAccessToken(HttpContext);
            //Get Access token from OAuth API response
            var generatedAccessToken = accessToken.GetGeneratedAccessToken();

            if (!string.IsNullOrWhiteSpace(generatedAccessToken))
            {
                using (var apiClient = new HttpClient())
                {
                    //API URL to Get K List Return
                    string requestUri = Constants.List_1099K_URL + "?BusinessId=" + businessId + "&Page=1&PageSize=10";
                    apiClient.BaseAddress = new Uri(apiUrl);
                    //Construct HTTP headers
                    OAuthGenerator.ConstructHeadersWithAccessToken(apiClient, generatedAccessToken);
                    //Get Response
                    var apiResponse = apiClient.GetAsync(requestUri).Result;

                    if (apiResponse != null && apiResponse.IsSuccessStatusCode)
                    {
                        //Read Response from API
                        var listResponse = apiResponse.Content.ReadAsAsync<Form1099KListResponse>().Result;
                        if (listResponse != null)
                        {
                            form1099KListResponseJSON = JsonConvert.SerializeObject(listResponse, Formatting.Indented);
                            form1099KListRepsone = JsonConvert.DeserializeObject<Form1099KListResponse>(form1099KListResponseJSON);
                        }
                    }
                    else
                    {
                        //Read Response from API
                        var listResponse = apiResponse.Content.ReadAsAsync<Form1099KListResponse>().Result;
                        form1099KListResponseJSON = JsonConvert.SerializeObject(listResponse, Formatting.Indented);
                        form1099KListRepsone = JsonConvert.DeserializeObject<Form1099KListResponse>(form1099KListResponseJSON);
                        var businessDetails = new Form1099KRecordsList();
                        form1099KListRepsone.Form1099Records = new List<Form1099KRecordsList>();
                        businessDetails.BusinessId = businessId;
                        businessDetails.BusinessNm = businessName;
                        businessDetails.FirstNm = firstName;
                        businessDetails.MiddleNm = MiddleName;
                        businessDetails.LastNm = lastName;
                        businessDetails.Suffix = suffix;
                        businessDetails.EINorSSN = tin;
                        form1099KListRepsone.Form1099Records.Add(businessDetails);
                    }
                }
            }

            return View(form1099KListRepsone);
        }
        #endregion

        #region Get KDetail By Submissionid and recordid
        [HttpGet]
        public IActionResult GetForm1099KDetail(Guid submissionId, Guid recordId)
        {
            var form1099KGetResponse = new Form1099KGetResponse();
            var states = new Form1099KStateDetail();
            var form1099KGetResponseJSON = string.Empty;
            var form1099KDetails = new Form1099KCreateRequest();
            //Get URLs from App.Config
            string apiUrl = Utility.GetAppSettings(Constants.TBS_PUBLIC_API_BASE_URL);
            //Get Access token from GetAccessToken Class
            GetAccessToken accessToken = new GetAccessToken(HttpContext);
            //Get Access token from OAuth API response
            var generatedAccessToken = accessToken.GetGeneratedAccessToken();

            if (!string.IsNullOrWhiteSpace(generatedAccessToken))
            {
                using (var apiClient = new HttpClient())
                {
                    //API URL to Get K Return using SubmissionId And RecordId
                    string requestUri = Constants.GET_1099K_URL + "?SubmissionId=" + submissionId + "&RecordIds=" + recordId;
                    apiClient.BaseAddress = new Uri(apiUrl);
                    //Construct HTTP headers
                    OAuthGenerator.ConstructHeadersWithAccessToken(apiClient, generatedAccessToken);
                    //Get Response
                    var apiResponse = apiClient.GetAsync(requestUri).Result;

                    if (apiResponse != null && apiResponse.IsSuccessStatusCode)
                    {
                        //Read Response from API
                        var getResponse = apiResponse.Content.ReadAsAsync<Form1099KGetResponse>().Result;
                        if (getResponse != null)
                        {
                            form1099KGetResponseJSON = JsonConvert.SerializeObject(getResponse, Formatting.Indented);
                            form1099KGetResponse = JsonConvert.DeserializeObject<Form1099KGetResponse>(form1099KGetResponseJSON);
                            if (form1099KDetails != null)
                            {
                                form1099KDetails.ReturnHeader = form1099KGetResponse.Form1099Records.ReturnHeader;
                                form1099KDetails.SubmissionManiFest = form1099KGetResponse.Form1099Records.SubmissionManifest;

form1099K-sdk/Form1099KSDK/Views/Form1099K/_Form1099KCreateResponse.cshtml
@model Form1099KSDK.Models.Form1099KCreate.Form1099KCreateResponse
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabel">Form1099K Create Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    <div class="table-container mt-2 mb-4">
        <table>
            <tbody>
                <tr class="fw-600 ">
                    <th class="text-center fw-600 bg-dull-blue" width="25%">Status Code</th>
                    <th class="text-center" width="30%">Status Name</th>
                    <th class="text-center">Status Message</th>
                </tr>
                <tr>
                    <td class="text-center align-top">
                        @Model.StatusCode
                    </td>
                    <td class="text-center align-top">
                        @Model.StatusName
                    </td>
                    @if (Model.StatusCode != 200)
                    {
                        <td class="text-center border-radious-bottom-right align-top text-danger">
                            @Model.StatusMessage
                        </td>
                    }
                    else
                    {
                        <td class="text-center border-radious-bottom-right align-top text-success">
                            @Model.StatusMessage
                        </td>
                    }
                </tr>
            </tbody>
        </table>
    </div>
    @if (Model != null)
    {
        if (Model.Errors != null && Model.Errors.Count > 0)
        {
            <h2 class="tabel-sub-head">Error</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.Errors)
                        {
                            <tr>
                                <td class="text-center align-top">@item.Id</td>
                                <td class="text-center align-top">@item.Name</td>
                                <td class="text-center border-radious-bottom-right align-top">@item.Message</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else if (Model.Form1099Records.ErrorRecords != null && Model.Form1099Records.ErrorRecords.Count > 0)
        {
            <h2 class="tabel-sub-head">Error Records</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.Form1099Records.ErrorRecords)
                        {
                            @foreach (var error in item.Errors)
                            {
                                <tr>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Id</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Name</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Message</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        }
    }
    @if (Model != null && Model.StatusCode == 200)
    {
        <h2 class="tabel-sub-head">Success Records</h2>
        <div class="table-container mb-3">
            <table>
                <tbody>
                    <tr class="fw-600 ">
                        <th class="text-center fw-600" width="30%">Submission Id</th>
                        <th class="text-center">Business Id</th>
                        <th class="text-center">Sequence Id</th>
                        <th class="text-center">Record Id</th>
                    </tr>
                    <tr>
                        <td class="text-center align-top">@Model.SubmissionId</td>
                        <td class="text-center align-top">@Model.BusinessId</td>
                        @foreach (var item in @Model.Form1099Records.SuccessRecords)
                        {
                            <td class="text-center border-radious-bottom-right align-top">@item.SequenceId</td>
                            <td class="text-center border-radious-bottom-right align-top">@item.RecordId</td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>

form1099K-sdk/Form1099KSDK/Views/Form1099K/_Form1099KDeleteResponse.cshtml
@model Form1099KSDK.Models.Form1099KDelete.Form1099KDeleteResponse
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabel">Form1099K Delete Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    <div class="table-container mt-2 mb-4">
        <table>
            <tbody>
                <tr class="fw-600 ">
                    <th class="text-center fw-600 bg-dull-blue" width="25%">Status Code</th>
                    <th class="text-center" width="30%">Status Name</th>
                    <th class="text-center">Status Message</th>
                </tr>
                <tr>
                    <td class="text-center align-top">
                        @Model.StatusCode
                    </td>
                    <td class="text-center align-top">
                        @Model.StatusName
                    </td>
                    @if (Model.StatusCode != 200)
                    {
                        <td class="text-center border-radious-bottom-right align-top text-danger">
                            @Model.StatusMessage
                        </td>
                    }
                    else
                    {
                        <td class="text-center border-radious-bottom-right align-top text-success">
                            @Model.StatusMessage
                        </td>
                    }
                </tr>
            </tbody>
        </table>
    </div>
    @if (Model != null)
    {
        if (Model.Errors != null && Model.Errors.Count > 0)
        {
            <h2 class="tabel-sub-head">Error</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.Errors)
                        {
                            <tr>
                                <td class="text-center align-top">@item.Id</td>
                                <td class="text-center align-top">@item.Name</td>
                                <td class="text-center border-radious-bottom-right align-top">@item.Message</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else if (Model.Form1099Records.ErrorRecords != null && Model.Form1099Records.ErrorRecords.Count > 0)
        {
            <h2 class="tabel-sub-head">Error Records</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.Form1099Records.ErrorRecords)
                        {
                            @foreach (var error in item.Errors)
                            {
                                <tr>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Id</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Name</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Message</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        }
    }
    @if (Model != null && Model.StatusCode == 200)
    {
        <h2 class="tabel-sub-head">Success Records</h2>
        <div class="table-container mb-3">
            <table>
                <tbody>
                    <tr class="fw-600 ">
                        <th class="text-center fw-600" width="30%">Submission Id</th>
                        <th class="text-center">Sequence Id</th>
                        <th class="text-center">Record Id</th>
                    </tr>
                    <tr>
                        <td class="text-center align-top">@Model.SubmissionId</td>
                        @foreach (var item in @Model.Form1099Records.SuccessRecords)
                        {
                            <td class="text-center border-radious-bottom-right align-top">@item.SequenceId</td>
                            <td class="text-center border-radious-bottom-right align-top">@item.RecordId</td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>

form1099K-sdk/Form1099KSDK/Views/Form1099K/_Form1099KDraftPdfResponse.cshtml
@model Form1099KSDK.Models.Form1099KDraftPdfUrl.RequestDraftPdfUrlResponse
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabel">Form1099K DraftPdf Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    @if (Model.Error != null)
    {
        <h2 class="tabel-sub-head">Error</h2>
        <div class="table-container mb-3">
            <table>
                <tbody>
                    <tr class="fw-600 ">
                        <th class="text-center fw-600" width="30%">Id</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Message</th>
                    </tr>
                    <tr>
                        <td class="text-center align-top">@Model.Error.Id</td>
                        <td class="text-center align-top">@Model.Error.Name</td>
                        <td class="text-center border-radious-bottom-right align-top">@Model.Error.Message</td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div class="table-container mb-3">
            <iframe src="@Url.Action("Form1099KRequestDraftPdfUrl", "Form1099K", new { DraftPdfUrl = Model.DraftPdfUrl})" style="width:100%;height:600px"></iframe>
        </div>
    }
</div>

form1099K-sdk/Form1099KSDK/Views/Form1099K/_Form1099KValidateFormResponse.cshtml
@model Form1099KSDK.Models.Form1099KCreate.Form1099KValidateFormResponse
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabel">Form1099K Validate Form Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    <div class="table-container mt-2 mb-4">
        <table>
            <tbody>
                <tr class="fw-600 ">
                    <th class="text-center fw-600 bg-dull-blue" width="25%">Status Code</th>
                    <th class="text-center" width="30%">Status Name</th>
                    <th class="text-center">Status Message</th>
                </tr>
                <tr>
                    <td class="text-center align-top">
                        @Model.StatusCode
                    </td>
                    <td class="text-center align-top">
                        @Model.StatusName
                    </td>
                    @if (Model.StatusCode != 200)
                    {
                        <td class="text-center border-radious-bottom-right align-top text-danger">
                            @Model.StatusMessage
                        </td>
                    }
                    else
                    {
                        <td class="text-center border-radious-bottom-right align-top text-success">
                            @Model.StatusMessage
                        </td>
                    }
                </tr>
            </tbody>
        </table>
    </div>
    @if (Model != null)
    {
        if (Model.Errors != null && Model.Errors.Count > 0)
        {
            <h2 class="tabel-sub-head">Error</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.Errors)
                        {
                            <tr>
                                <td class="text-center align-top">@item.Id</td>
                                <td class="text-center align-top">@item.Name</td>
                                <td class="text-center border-radious-bottom-right align-top">@item.Message</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else if (Model.ErrorRecords != null && Model.ErrorRecords.Count > 0)
        {
            <h2 class="tabel-sub-head">Error Records</h2>
            <div class="table-container mb-3">
                <table>
                    <tbody>
                        <tr class="fw-600 ">
                            <th class="text-center fw-600" width="30%">Id</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Message</th>
                        </tr>
                        @foreach (var item in Model.ErrorRecords)
                        {
                            @foreach (var error in item.Errors)
                            {
                                <tr>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Id</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Name</td>
                                    <td class="text-center border-radious-bottom-right align-top">@error.Message</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        }
    }
</div>

form1099K-sdk/Form1099KSDK/Views/Form1099K/_ViewRequestPdfUrl.cshtml
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalToggleLabel">Form1099K RequestPdfUrl Response</h5>
    <button type="button" class="btn-close bg-white rounded-circle border-0 fw-bold position-absolute end-n-10 top-n-13 modal-close button-hide fs-18 fw-500" data-bs-dismiss="modal" aria-label="Close">X</button>
</div>
<div class="modal-body">
    @if (TempData["PdfUrl"] != null)
    {
        <div>
            <iframe src="@Url.Action("RequestPdfUrls", "Form1099K", new { PdfUrl = TempData["PdfUrl"]})" style="width:100%;height:600px"></iframe>
        </div>
    }
</div>